### PR TITLE
Add watchOS and tvOS to the party!

### PR DESCRIPTION
**Pull request by SlaunchaMan**
This PR adds watchOS and tvOS support to LoremIpsum.

### CODE REVIEW

**Comment by lukaskubanek** [comment]
@SlaunchaMan: Hi Jeff, I’m in the process of spring cleaning my open source projects. I just refreshed [LoremSwiftum](https://github.com/lukaskubanek/LoremSwiftum) which I’m still using in my projects but I no longer have use for LoremIpsum. As you’ve been quite active with PRs I was wondering whether you’d like to become a co-maintainer of this library?

**Comment by lukaskubanek** [comment]
@SlaunchaMan: After posting my comment I noticed that I’ve already asked you the same question and [you agreed](https://github.com/lukaskubanek/LoremIpsum/pull/15#issuecomment-411187591). Is this still the case?

**Comment by SlaunchaMan** [comment]
@lukaskubanek Sure thing! Looks like I also need to freshen up this PR.

**Comment by lukaskubanek** [comment]
@SlaunchaMan: I’ve added you as a maintainer of this repository. Feel free to do whatever you think is the best for the library.

**Comment by SlaunchaMan** [comment]
@lukaskubanek Everything is all set for a 2.0 release, but I don’t have access to do the `pod trunk push`. Want to do the honors?

**Comment by SlaunchaMan** [comment]
@lukaskubanek It worked! 🎉

**Pull request merged**
